// src/components/PredictModal.tsx
import React, { useState, useEffect } from 'react';
import { X, Sparkles, RefreshCw, Check, Loader2, Zap, Layers, Cpu, ShieldCheck, CheckCircle2 } from 'lucide-react';
import confetti from 'canvas-confetti';
import { PredictionRecord, PredictionSet } from '../types';
import { generatePredictionBoards, BOARD_PRICE_ZAR, formatZAR } from '../utils/lottoEngine';
import { LottoBall } from './LottoBall';

interface PredictModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSavePrediction: (prediction: PredictionRecord) => void;
  targetDrawDate: string;
}

type ModalStep = 'setup' | 'analyzing' | 'complete';

export const PredictModal: React.FC<PredictModalProps> = ({
  isOpen,
  onClose,
  onSavePrediction,
  targetDrawDate,
}) => {
  const [step, setStep] = useState<ModalStep>('setup');
  const [boardCount, setBoardCount] = useState<number>(3);
  const [strategy, setStrategy] = useState<'ensemble' | 'hot_cold' | 'delta_spread'>('ensemble');
  const [analysisProgress, setAnalysisProgress] = useState<number>(0);
  const [currentAnalysisStage, setCurrentAnalysisStage] = useState<string>('Analyzing dataset rules...');
  const [generatedSets, setGeneratedSets] = useState<PredictionSet[]>([]);

  // Reset modal when reopened
  useEffect(() => {
    if (isOpen) {
      setStep('setup');
      setAnalysisProgress(0);
      setGeneratedSets([]);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleStartGeneration = () => {
    setStep('analyzing');
    setAnalysisProgress(10);
    setCurrentAnalysisStage('🌀 Analyzing dataset rules & frequency distributions...');

    const stages = [
      { progress: 28, text: '🌀 Evaluating historical hot & cold number frequencies (1-36)...' },
      { progress: 55, text: '🧠 Applying delta sequence & odd/even parity filters...' },
      { progress: 78, text: '⚡ Eliminating low-probability sums (ideal: 65 - 120)...' },
      { progress: 95, text: '✨ Synthesizing top candidate boards with ensemble scoring...' },
      { progress: 100, text: '✓ Generation finalized and indexed.' },
    ];

    let currentIdx = 0;
    const interval = setInterval(() => {
      if (currentIdx < stages.length) {
        setAnalysisProgress(stages[currentIdx].progress);
        setCurrentAnalysisStage(stages[currentIdx].text);
        currentIdx++;
      } else {
        clearInterval(interval);
        // Create candidate sets
        const sets = generatePredictionBoards(boardCount);
        setGeneratedSets(sets);
        setStep('complete');

        // Trigger celebratory confetti
        confetti({
          particleCount: 60,
          spread: 70,
          origin: { y: 0.6 },
          colors: ['#10b981', '#34d399', '#6ee7b7', '#f59e0b'],
        });
      }
    }, 450);
  };

  const handleRedo = () => {
    handleStartGeneration();
  };

  const handleDone = () => {
    const cost = boardCount * BOARD_PRICE_ZAR;
    const newPrediction: PredictionRecord = {
      id: `pred-${Date.now()}`,
      createdAt: new Date().toISOString(),
      targetDrawDate,
      boardsCount: boardCount,
      cost,
      sets: generatedSets,
      status: 'pending',
      totalWon: 0,
      netProfit: -cost,
      topMatchCount: 0,
    };

    onSavePrediction(newPrediction);
    onClose();
  };

  return (
    <div
      id="modal-predict-next-draw"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/80 backdrop-blur-sm animate-in fade-in duration-200"
    >
      <div
        id="modal-content-card"
        className="w-full max-w-md bg-zinc-900 border border-zinc-800 rounded-2xl shadow-2xl p-5 relative overflow-hidden flex flex-col max-h-[90vh]"
      >
        {/* Subtle top glow */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-indigo-500/10 via-indigo-500 to-purple-500/10" />

        {/* Modal Header */}
        <div className="flex items-center justify-between pb-3 border-b border-zinc-800/80 mb-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/15 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-black uppercase tracking-wider text-zinc-100">
                Generate Prediction
              </h3>
              <p className="text-[11px] font-mono text-zinc-400">
                Target: <span className="text-indigo-400 font-bold">{targetDrawDate}</span> • 5/36 SA Daily Lotto
              </p>
            </div>
          </div>

          <button
            id="btn-close-predict-modal"
            onClick={onClose}
            className="p-1.5 rounded-lg text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body based on Step */}
        {step === 'setup' && (
          <div id="predict-step-setup" className="space-y-4 my-1">
            {/* Number of Draws / Boards */}
            <div className="p-3.5 rounded-xl bg-zinc-950/70 border border-zinc-800">
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-bold text-zinc-200 uppercase tracking-wide">
                  Number of Draws / Boards to Predict
                </label>
                <span className="text-xs font-mono font-bold text-indigo-400">
                  {boardCount} Boards ({formatZAR(boardCount * BOARD_PRICE_ZAR)})
                </span>
              </div>

              {/* Board count chips */}
              <div className="grid grid-cols-4 gap-2">
                {[1, 3, 5, 10].map((num) => (
                  <button
                    key={`board-option-${num}`}
                    type="button"
                    onClick={() => setBoardCount(num)}
                    className={`py-2 rounded-lg text-xs font-mono font-bold transition-all border ${
                      boardCount === num
                        ? 'bg-gradient-to-r from-indigo-500 to-purple-600 text-white border-indigo-400 shadow-md shadow-indigo-500/20'
                        : 'bg-zinc-900 hover:bg-zinc-800 text-zinc-300 border-zinc-800'
                    }`}
                  >
                    {num === 3 ? `${num} (Std)` : `${num} B`}
                  </button>
                ))}
              </div>
            </div>

            {/* Strategy Selection */}
            <div className="p-3.5 rounded-xl bg-zinc-950/70 border border-zinc-800 space-y-2">
              <label className="text-xs font-bold text-zinc-200 uppercase tracking-wide flex items-center gap-1.5">
                <Cpu className="w-3.5 h-3.5 text-indigo-400" />
                <span>AI Algorithmic Model</span>
              </label>

              <div className="grid grid-cols-3 gap-2">
                {[
                  { id: 'ensemble', name: 'Ensemble AI', desc: 'Balanced' },
                  { id: 'hot_cold', name: 'Hot/Cold Heat', desc: 'Recency' },
                  { id: 'delta_spread', name: 'Delta Spread', desc: 'Variance' },
                ].map((strat) => (
                  <button
                    key={strat.id}
                    type="button"
                    onClick={() => setStrategy(strat.id as any)}
                    className={`p-2 rounded-lg text-left transition-all border ${
                      strategy === strat.id
                        ? 'bg-indigo-950/50 border-indigo-500/60 text-indigo-300'
                        : 'bg-zinc-900/60 hover:bg-zinc-800 text-zinc-400 border-zinc-800/80'
                    }`}
                  >
                    <div className="text-[11px] font-bold truncate text-zinc-200">{strat.name}</div>
                    <div className="text-[9px] font-mono text-zinc-500">{strat.desc}</div>
                  </button>
                ))}
              </div>
            </div>

            {/* Execution CTA Button */}
            <button
              id="btn-execute-generation"
              onClick={handleStartGeneration}
              className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-gradient-to-r from-indigo-500 via-indigo-600 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-black text-sm uppercase tracking-wider shadow-lg shadow-indigo-500/25 transition-all duration-150 active:scale-[0.98]"
            >
              <Zap className="w-4 h-4 fill-white" />
              <span>Generate Predictions</span>
            </button>
          </div>
        )}

        {/* Step 2: Analyzing / Streaming Execution */}
        {step === 'analyzing' && (
          <div id="predict-step-analyzing" className="py-8 px-2 flex flex-col items-center justify-center text-center space-y-4">
            <div className="relative flex items-center justify-center w-16 h-16 rounded-full bg-indigo-500/10 border border-indigo-500/30">
              <Loader2 className="w-8 h-8 text-indigo-400 animate-spin" />
              <Sparkles className="w-4 h-4 text-indigo-300 absolute" />
            </div>

            <div className="space-y-1 max-w-xs">
              <div className="text-sm font-black text-zinc-100 font-mono tracking-tight animate-pulse">
                {currentAnalysisStage}
              </div>
              <p className="text-xs text-zinc-500 font-mono">
                Running 10,000 Monte-Carlo simulations against 1-36 Daily Lotto bounds...
              </p>
            </div>

            {/* Animated Progress Bar */}
            <div className="w-full bg-zinc-800 rounded-full h-2 overflow-hidden border border-zinc-700">
              <div
                className="bg-gradient-to-r from-indigo-500 to-purple-500 h-full transition-all duration-300 rounded-full"
                style={{ width: `${analysisProgress}%` }}
              />
            </div>

            <div className="flex items-center gap-2 text-xs font-mono text-zinc-400">
              <span>Progress: {analysisProgress}%</span>
              <span>•</span>
              <span className="text-indigo-400">Target: {boardCount} Sets</span>
            </div>
          </div>
        )}

        {/* Step 3: Complete / Candidate Sets */}
        {step === 'complete' && (
          <div id="predict-step-complete" className="space-y-3.5 my-1 flex flex-col">
            <div className="flex items-center justify-between p-2.5 rounded-xl bg-indigo-500/15 border border-indigo-500/30 text-indigo-300 text-xs font-bold font-mono">
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-indigo-400" />
                <span>✓ {generatedSets.length} Candidates generated & saved!</span>
              </span>
              <span className="text-[11px] text-zinc-300">{formatZAR(boardCount * BOARD_PRICE_ZAR)}</span>
            </div>

            {/* Generated Sets List */}
            <div className="space-y-2 max-h-[260px] overflow-y-auto pr-1">
              {generatedSets.map((set, idx) => (
                <div
                  key={set.id || `gen-${idx}`}
                  id={`generated-candidate-set-${idx + 1}`}
                  className="p-3 rounded-xl bg-zinc-950/80 border border-zinc-800 flex flex-col gap-2"
                >
                  <div className="flex items-center justify-between text-xs font-mono">
                    <span className="font-bold text-zinc-200">Set #{set.setNumber || idx + 1}</span>
                    <span className="text-indigo-400 font-bold">Conf: {set.confidenceScore}%</span>
                  </div>

                  <div className="flex items-center justify-between gap-1.5">
                    {set.numbers.map((num) => (
                      <LottoBall
                        key={`gen-set-${idx}-ball-${num}`}
                        number={num}
                        size="md"
                        variant="emerald"
                      />
                    ))}
                  </div>
                </div>
              ))}
            </div>

            {/* Actions: Redo & Done */}
            <div className="grid grid-cols-2 gap-2 pt-2 border-t border-zinc-800">
              <button
                id="btn-redo-prediction"
                onClick={handleRedo}
                className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-bold text-xs uppercase tracking-wider border border-zinc-700 transition-colors"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>[ 🔄 Redo ]</span>
              </button>

              <button
                id="btn-done-prediction"
                onClick={handleDone}
                className="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-black text-xs uppercase tracking-wider shadow-md shadow-indigo-500/20 transition-colors"
              >
                <Check className="w-4 h-4 stroke-[3]" />
                <span>[ ✓ Done ]</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// src/components/PredictModal.vue
<script setup>
import { ref, watch } from 'vue';
import {
  Sparkles,
  Zap,
  RotateCcw,
  Check,
  Cpu,
  Loader2,
  X,
  CheckCircle2,
} from 'lucide-vue-next';
import confetti from 'canvas-confetti';
import LottoBall from './LottoBall.vue';
import {
  BOARD_PRICE_ZAR,
  generatePredictionBoards,
  generateCandidateSet,
  formatZAR,
} from '../utils/lottoEngine';

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true,
  },
  targetDrawDate: {
    type: String,
    required: true,
  },
  onClose: {
    type: Function,
    required: true,
  },
  onSavePrediction: {
    type: Function,
    required: true,
  },
});

const step = ref('config'); // 'config' | 'analyzing' | 'complete'
const boardCount = ref(3);
const strategy = ref('balanced');
const analysisProgress = ref(0);
const analysisMessage = ref('Initializing historical pattern engine...');
const generatedSets = ref([]);

watch(
  () => props.isOpen,
  (newVal) => {
    if (newVal) {
      step.value = 'config';
      analysisProgress.value = 0;
      generatedSets.value = [];
    }
  }
);

const handleStartGeneration = () => {
  step.value = 'analyzing';
  analysisProgress.value = 10;
  analysisMessage.value = 'Scanning 5/36 frequency matrix & hot numbers...';

  const t1 = setTimeout(() => {
    analysisProgress.value = 45;
    analysisMessage.value = 'Calculating combinatoric delta & odd/even balance...';
  }, 450);

  const t2 = setTimeout(() => {
    analysisProgress.value = 80;
    analysisMessage.value = 'Optimizing 3-board synergy to maximize coverage...';
  }, 950);

  const t3 = setTimeout(() => {
    analysisProgress.value = 100;
    analysisMessage.value = 'Prediction complete!';

    // Generate real candidate boards
    const sets = generatePredictionBoards(boardCount.value);
    generatedSets.value = sets;
    step.value = 'complete';

    // Celebration confetti
    try {
      confetti({
        particleCount: 45,
        spread: 60,
        origin: { y: 0.65 },
        colors: ['#F6BD51', '#FFB59E', '#B7E1D2', '#D2CFF7'],
      });
    } catch {
      // Ignore if canvas unavailable
    }
  }, 1450);
};

const handleRegenerateSingleSet = (setIdx) => {
  const newSet = generateCandidateSet(setIdx + 1, strategy.value);
  const updated = [...generatedSets.value];
  updated[setIdx] = newSet;
  generatedSets.value = updated;
};

const handleDone = () => {
  const newPredictionRecord = {
    id: `pred-${Date.now()}`,
    createdAt: new Date().toISOString(),
    targetDrawDate: props.targetDrawDate,
    boardsCount: boardCount.value,
    cost: boardCount.value * BOARD_PRICE_ZAR,
    sets: generatedSets.value,
    status: 'pending',
    totalWon: 0,
    netProfit: -(boardCount.value * BOARD_PRICE_ZAR),
    topMatchCount: 0,
  };

  props.onSavePrediction(newPredictionRecord);
  props.onClose();
  step.value = 'config';
};

const handleCloseModal = () => {
  props.onClose();
  step.value = 'config';
};
</script>

<template>
  <div
    v-if="isOpen"
    id="modal-predict-next-draw"
    class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-in fade-in duration-200"
  >
    <div
      id="modal-predict-container"
      class="w-full max-w-md bg-white border border-[#E7DFD5] rounded-3xl shadow-xl p-5 relative overflow-hidden flex flex-col max-h-[90vh] text-[#2C211C]"
    >
      <!-- Modal Header -->
      <div class="flex items-center justify-between pb-3 border-b border-[#E7DFD5] mb-3.5">
        <div class="flex items-center gap-2.5">
          <div class="w-8 h-8 rounded-full bg-[#FFF3D9] border border-[#F6BD51]/40 flex items-center justify-center text-[#2C211C]">
            <Sparkles class="w-4 h-4 text-[#F6BD51]" />
          </div>
          <div>
            <h3 class="text-xs font-black uppercase tracking-wider text-[#2C211C]">
              AI PREDICTION GENERATOR
            </h3>
            <p class="text-[10px] text-[#786C65] font-semibold">
              Target: <span class="text-[#2C211C] font-black">{{ targetDrawDate }}</span> • 5/36 SA Daily Lotto
            </p>
          </div>
        </div>

        <button
          id="btn-close-predict-modal"
          @click="handleCloseModal"
          class="p-1 rounded-full text-[#786C65] hover:text-[#2C211C] hover:bg-[#FAF5EE] transition-colors cursor-pointer"
        >
          <X class="w-5 h-5" />
        </button>
      </div>

      <!-- Step 1: Configuration Form -->
      <div v-if="step === 'config'" id="predict-step-config" class="space-y-3.5 my-1">
        <!-- Number of Boards Selector -->
        <div class="space-y-1.5">
          <div class="flex items-center justify-between">
            <label class="text-[11px] font-bold text-[#2C211C] uppercase tracking-wide">
              Board Count Allocation
            </label>
            <span class="text-xs font-black text-[#2C211C]">
              {{ boardCount }} Boards ({{ formatZAR(boardCount * BOARD_PRICE_ZAR) }})
            </span>
          </div>

          <div class="grid grid-cols-3 gap-2">
            <button
              v-for="num in [1, 3, 5]"
              :key="num"
              :id="`btn-select-board-count-${num}`"
              type="button"
              @click="boardCount = num"
              :class="[
                'py-2 rounded-full text-xs font-bold transition-all border cursor-pointer',
                boardCount === num
                  ? 'bg-[#2C211C] text-white border-[#2C211C] shadow-xs'
                  : 'bg-[#FAF5EE] hover:bg-[#F4EFE6] text-[#786C65] border-[#EADBCC]'
              ]"
            >
              {{ num }} {{ num === 1 ? 'Board (R3)' : 'Boards (R' + num * 3 + ')' }}
            </button>
          </div>
        </div>

        <!-- Strategy Selection -->
        <div class="p-3.5 rounded-2xl bg-[#FAF5EE] border border-[#EADBCC] space-y-2">
          <label class="text-[11px] font-extrabold text-[#2C211C] uppercase tracking-wide flex items-center gap-1.5">
            <Cpu class="w-3.5 h-3.5 text-[#F6BD51]" />
            <span>Optimization Heuristic</span>
          </label>

          <div class="space-y-1.5 text-xs">
            <button
              v-for="strat in [
                { id: 'balanced', name: 'Balanced Frequency', desc: 'Combines hot 30-day pairs with cold resurgence' },
                { id: 'hot', name: 'Hot Velocity Cluster', desc: 'Prioritizes highest rolling 7-day draw frequencies' },
                { id: 'frequency', name: 'Low Delta Distribution', desc: 'Even dispersion across 1-36 decade blocks' },
              ]"
              :key="strat.id"
              :id="`btn-strategy-${strat.id}`"
              type="button"
              @click="strategy = strat.id"
              :class="[
                'w-full p-2.5 rounded-xl text-left transition-all border cursor-pointer',
                strategy === strat.id
                  ? 'bg-white border-[#F6BD51] shadow-xs text-[#2C211C]'
                  : 'bg-white/60 hover:bg-white text-[#786C65] border-[#EADBCC]'
              ]"
            >
              <div class="font-bold text-[#2C211C] text-[11px]">{{ strat.name }}</div>
              <div class="text-[10px] text-[#786C65]">{{ strat.desc }}</div>
            </button>
          </div>
        </div>

        <!-- Generate Action Button -->
        <button
          id="btn-execute-generation"
          @click="handleStartGeneration"
          class="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-full bg-[#F6BD51] hover:bg-[#F4B238] text-[#2C211C] font-black text-xs uppercase tracking-wider shadow-sm transition-all duration-150 active:scale-98 cursor-pointer border border-[#E5A836]"
        >
          <Zap class="w-4 h-4 fill-[#2C211C]" />
          <span>Execute AI Prediction</span>
        </button>
      </div>

      <!-- Step 2: Analyzing / Streaming Execution -->
      <div
        v-if="step === 'analyzing'"
        id="predict-step-analyzing"
        class="py-8 px-2 flex flex-col items-center justify-center text-center space-y-4"
      >
        <div class="relative flex items-center justify-center w-16 h-16 rounded-full bg-[#FFF3D9] border border-[#F6BD51]/40">
          <Loader2 class="w-8 h-8 text-[#F6BD51] animate-spin" />
          <Sparkles class="w-4 h-4 text-[#F6BD51] absolute" />
        </div>

        <div class="space-y-1 max-w-xs">
          <h4 class="text-xs font-black uppercase text-[#2C211C]">
            Running Algorithmic Simulation
          </h4>
          <p class="text-[11px] text-[#786C65] font-semibold">
            {{ analysisMessage }}
          </p>
        </div>

        <!-- Animated Progress Bar in peach -->
        <div class="w-full bg-[#FAF5EE] rounded-full h-3 p-0.5 border border-[#EADBCC]">
          <div
            class="bg-[#FFB59E] h-full transition-all duration-300 rounded-full border border-[#F0A48C]"
            :style="{ width: `${analysisProgress}%` }"
          />
        </div>
        <div class="flex items-center gap-2 text-[10px] font-bold text-[#786C65]">
          <span>Progress: {{ analysisProgress }}%</span>
          <span>•</span>
          <span class="text-[#2C211C]">Target: {{ boardCount }} Sets</span>
        </div>
      </div>

      <!-- Step 3: Complete / Candidate Sets -->
      <div
        v-if="step === 'complete'"
        id="predict-step-complete"
        class="space-y-3 my-1 flex flex-col"
      >
        <div class="flex items-center justify-between p-2.5 rounded-2xl bg-[#E8F5E9] border border-[#C8E6C9] text-[#2E7D32] text-xs font-bold">
          <span class="flex items-center gap-1.5">
            <CheckCircle2 class="w-4 h-4 text-[#2E7D32]" />
            <span>✓ {{ generatedSets.length }} Candidates generated & locked!</span>
          </span>
          <span class="text-[11px] text-[#2C211C] font-black">{{ formatZAR(boardCount * BOARD_PRICE_ZAR) }}</span>
        </div>

        <!-- Scrollable Candidate Sets List -->
        <div class="space-y-2 max-h-[300px] overflow-y-auto pr-1">
          <div
            v-for="(set, idx) in generatedSets"
            :key="set.id"
            :id="`generated-board-${idx + 1}`"
            class="p-3 rounded-2xl bg-[#FAF5EE] border border-[#EADBCC] space-y-2"
          >
            <div class="flex items-center justify-between text-xs">
              <span class="font-black text-[#2C211C]">Board #{{ set.setNumber || idx + 1 }}</span>
              <span class="text-[10px] font-bold text-[#786C65] bg-white px-2 py-0.5 rounded-full border border-[#E7DFD5]">
                Synergy: <strong class="text-[#2C211C]">{{ set.confidenceScore }}%</strong>
              </span>
            </div>

            <div class="flex items-center justify-between gap-1.5">
              <LottoBall
                v-for="(num, bIdx) in set.numbers"
                :key="`gen-ball-${idx}-${num}`"
                :number="num"
                size="md"
                :variant="bIdx === 0 ? 'peach' : bIdx === 1 ? 'mint' : bIdx === 2 ? 'lavender' : bIdx === 3 ? 'rose' : 'gold'"
              />
            </div>

            <!-- Single board regeneration -->
            <div class="flex justify-end pt-0.5">
              <button
                :id="`btn-reroll-set-${idx + 1}`"
                @click="handleRegenerateSingleSet(idx)"
                class="flex items-center gap-1 text-[10px] font-bold text-[#786C65] hover:text-[#2C211C] px-2 py-1 rounded-full bg-white border border-[#E7DFD5] transition-colors cursor-pointer"
                title="Reroll this specific board"
              >
                <RotateCcw class="w-3 h-3 text-[#786C65]" />
                <span>Reroll Set</span>
              </button>
            </div>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="grid grid-cols-2 gap-2 pt-1">
          <button
            id="btn-re-generate-all"
            @click="handleStartGeneration"
            class="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-full bg-[#FAF5EE] hover:bg-[#F4EFE6] text-[#2C211C] font-bold text-xs uppercase tracking-wide transition-colors border border-[#E7DFD5] cursor-pointer"
          >
            <RotateCcw class="w-3.5 h-3.5" />
            <span>Reroll All</span>
          </button>

          <button
            id="btn-done-prediction"
            @click="handleDone"
            class="flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-full bg-[#F6BD51] hover:bg-[#F4B238] text-[#2C211C] font-black text-xs uppercase tracking-wider shadow-xs transition-colors border border-[#E5A836] cursor-pointer"
          >
            <Check class="w-4 h-4 stroke-[3]" />
            <span>Accept Candidates</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
